#!/usr/bin/env python3

# Import the necessary libraries
import time
import math
from ev3dev2.motor import *
from ev3dev2.sound import Sound
from ev3dev2.button import Button
from ev3dev2.sensor import *
from ev3dev2.sensor.lego import *
from ev3dev2.sensor.virtual import *

# Create the sensors and motors objects
motorA = LargeMotor(OUTPUT_A)
motorB = LargeMotor(OUTPUT_B)
left_motor = motorA
right_motor = motorB
tank_drive = MoveTank(OUTPUT_A, OUTPUT_B)
steering_drive = MoveSteering(OUTPUT_A, OUTPUT_B)

spkr = Sound()
btn = Button()
radio = Radio()
obtr = ObjectTracker()

color_sensor_in1 = ColorSensor(INPUT_1)
ultrasonic_sensor_in2 = UltrasonicSensor(INPUT_2)
gyro_sensor_in3 = GyroSensor(INPUT_3)
gps_sensor_in4 = GPSSensor(INPUT_4)
pen_in5 = Pen(INPUT_5)

motorC = LargeMotor(OUTPUT_C) # Magnet

# Here is where your code starts
print("")
print("program started")

def turn(sp, times, k):
    print("turning function called, sp: ", sp, ", times: ", times, ", k: ", k)
    for i in range(times):
        pv = gyro_sensor_in3.angle
        e = sp - pv
        speed = e * k
        speed = max(-100, min(speed, 100))
        tank_drive.on(speed, -speed)
        
        if pv == sp:
            print("finished turning at angle: ", pv, ", on itiration: ", i)
            break

#turn(67, 1000, 1)
#turn(-67, 1000, 1)
#turn(0, 1000, 1)
